"""Protein network from an amino-acid sequence, one call.

``build_protein_network`` is the entry point behind ``topon protein`` and
``python -m topon.protein_network build``. It takes a one-letter sequence (a
repeat block with ``repeats``, or a whole chain), lays the chain out on the
residue-level lattice melt, one site per residue, crosslinks the
crosslink residues that touch (``crosslink_method="melt"``, the default
since 0.4.0, :func:`bfm.generate_melt_topology`), or lays the chain out on the
BFM node lattice with a crosslinkable node at every crosslink residue
(:func:`sequence.plan_chain`) and crosslinks it there (``adjacent`` and the
other :mod:`bfm` methods), and builds it with either model:

* ``model="charmm"``: CHARMM36m all-atom (TIP3P and NaCl if hydrated), the
  crosslink applied as its RTF patch (DITY for Tyr, DISU for Cys), every term
  looked up by :mod:`topon.forcefield.charmm`;
* ``model="martini"``: Martini 3 with the Martini3-IDP bonded terms, one
  polyply chain topology per chain (vendored for the resilin reference,
  generated by polyply otherwise), Martini water and ions.

Both write a LAMMPS data file, coefficient includes, groups and three
relaxation scripts, plus ``protein_network_summary.json`` recording the
inputs, the snapshot used, counts, charges and file names. The build is
deterministic for a given ``seed``.
"""
from __future__ import annotations

import json
import shutil
import warnings
from dataclasses import asdict, dataclass, field
from pathlib import Path

from . import bfm, sequence, topology_io

MODELS = ("charmm", "martini")
CROSSLINK_METHODS = ("adjacent", "winding_safe", "distance", "none", "melt")
#: Residues each model knows how to crosslink.
CROSSLINK_RESIDUES = {"charmm": ("Y", "C"), "martini": ("Y", "C")}


@dataclass
class ProteinNetworkSettings:
    """Every input of :func:`build_protein_network` (also the JSON config)."""
    sequence: str
    model: str = "martini"
    repeats: int = 1
    chains: int = 8
    crosslink_residue: str = "Y"
    crosslink_method: str = "melt"
    snapshot: str = "gel_point"
    #: build the last snapshot when the one asked for (the gel point by
    #: default) was not reached, instead of stopping
    allow_no_gel: bool = False
    seed: int = 42
    output_dir: str = "protein_network"
    segs_per_block: int = 2
    residues_per_segment: float | None = None
    equil_steps: int = 20_000
    target_packing: float = 0.45
    n_extra_snapshots: int = 2
    snapshot_delta_conv: float = 0.05
    min_intrachain_sep: int = 2
    #: melt only: crosslink residues this close (lattice units, one unit a
    #: residue step) may crosslink; 1.5 is face and edge neighbours
    contact_radius: float = 1.5
    water_content: float = 0.0
    salt_conc: float = 0.15
    target_density: float = 0.85
    # CHARMM
    physical_backbone: bool = True
    xpro_cis_fraction: float = 0.0
    charmm_files: list[str] = field(default_factory=list)
    # MARTINI
    martini_itp: str | None = None
    water_bead: str = "W"
    hierarchical_stage1: bool = True

    def check(self) -> None:
        if self.model not in MODELS:
            raise ValueError(f"model must be one of {MODELS}, got {self.model!r}")
        if self.crosslink_method not in CROSSLINK_METHODS:
            raise ValueError(f"crosslink_method must be one of {CROSSLINK_METHODS}")
        x = self.crosslink_residue.upper()
        if self.crosslink_method != "none" and x not in CROSSLINK_RESIDUES[self.model]:
            raise ValueError(
                f"the {self.model} model crosslinks {CROSSLINK_RESIDUES[self.model]} "
                f"(dityrosine, disulfide), not {x!r}")
        if not 1.0 <= self.contact_radius <= 6.0:
            raise ValueError("contact_radius is in lattice units, 1 to 6")
        if not 0.0 <= self.water_content < 100.0:
            raise ValueError("water_content is a weight percent in [0, 100)")
        if self.chains < 1 or self.repeats < 1:
            raise ValueError("chains and repeats must be at least 1")
        if self.model == "martini" and self.martini_itp is None and "W" in self.sequence.upper():
            # checked before the lattice is built; a user ITP is checked when read
            raise ValueError("Martini 3 tryptophan (W) needs virtual sites, which LAMMPS "
                             "cannot represent; use a sequence without W or the CHARMM model")

    @classmethod
    def from_json(cls, path: str | Path) -> "ProteinNetworkSettings":
        data = json.loads(Path(path).read_text(encoding="utf-8"))
        data = data.get("protein_network", data)
        known = set(cls.__dataclass_fields__)
        extra = sorted(set(data) - known - {"comment"})
        if extra:
            raise ValueError(f"unknown protein-network keys {extra}; known: {sorted(known)}")
        return cls(**{k: v for k, v in data.items() if k in known})


def _connectivity(snap: dict) -> dict:
    """Clusters of chains joined by the snapshot's crosslinks."""
    info = bfm.analyze_connectivity(snap)
    n = len(snap["chains"])
    return {"n_clusters": info["n_components"],
            "largest_cluster_chains": round(info["largest_cluster_frac"] * n), "n_chains": n}


def _pick_snapshot(topology: dict, wanted: str | int, method: str, allow_no_gel: bool = False):
    """The snapshot to build, and a note when it is not the one asked for.

    A snapshot that was not reached (a network that never gels) stops the
    build unless ``allow_no_gel``, in which case the last snapshot is built.
    """
    if method == "none":
        return topology["snapshots"][0], None
    try:
        label = int(wanted)
    except (TypeError, ValueError):
        label = wanted
    try:
        return topology_io.get_snapshot(topology, label), None
    except (KeyError, IndexError):
        snap = topology["snapshots"][-1]
        c = _connectivity(snap)
        state = (f"the last snapshot ({snap['label']!r}, conversion {snap['conv']:.3f}) has "
                 f"{c['n_clusters']} clusters, the largest holding "
                 f"{c['largest_cluster_chains']} of {c['n_chains']} chains")
        if not allow_no_gel:
            knob = ("a larger --contact-radius" if method == "melt"
                    else "more --equil-steps")
            raise ValueError(
                f"snapshot {wanted!r} was not reached, so the chains do not form one "
                f"network: {state}. Use more repeats, another --seed or {knob}, or "
                f"pass --allow-no-gel to build that snapshot anyway.")
        note = f"snapshot {wanted!r} was not reached; built the last one instead: {state}"
        warnings.warn(note, RuntimeWarning, stacklevel=3)
        return snap, note


def build_protein_network(settings: ProteinNetworkSettings | None = None, *,
                          verbose: bool = True, **kwargs) -> dict:
    """Build a protein network from a sequence; return the summary dict.

    Pass a :class:`ProteinNetworkSettings` or its fields as keyword arguments
    (``build_protein_network(sequence="GGRPSDSYGAPGGGN", repeats=18,
    model="charmm")``).
    """
    s = settings or ProteinNetworkSettings(**kwargs)
    if settings is not None and kwargs:
        raise TypeError("give either settings or keyword arguments, not both")
    s.check()
    out = Path(s.output_dir)
    out.mkdir(parents=True, exist_ok=True)

    plan = sequence.plan_chain(
        s.sequence, repeats=s.repeats, crosslink_residue=s.crosslink_residue,
        segs_per_block=s.segs_per_block, residues_per_segment=s.residues_per_segment,
    )
    if not plan.y_positions and s.crosslink_method != "none":
        raise ValueError(
            f"the chain has no crosslinkable {plan.crosslink_residue} away from its "
            f"ends; use crosslink_method='none' or another crosslink residue")
    if verbose:
        print(f"[protein] {s.model}: {s.chains} chains x {plan.n_residues} residues, "
              f"{len(plan.y_positions)} crosslink sites per chain ({plan.layout} layout)")

    if s.crosslink_method == "melt":
        # one lattice site per residue, so the builders map node i to residue i
        topology = bfm.generate_melt_topology(
            plan, s.chains, target_packing=s.target_packing,
            n_extra_snapshots=s.n_extra_snapshots, snapshot_delta_conv=s.snapshot_delta_conv,
            min_intrachain_sep=s.min_intrachain_sep, contact_radius=s.contact_radius,
            seed=s.seed, verbose=verbose)
        node_to_res = {i: i for i in range(plan.n_residues)}
        layout, n_nodes = "residues", plan.n_residues
    else:
        topology = bfm.generate_topology_for_plan(
            plan, s.chains,
            target_packing=s.target_packing, equil_steps=s.equil_steps,
            n_extra_snapshots=s.n_extra_snapshots, snapshot_delta_conv=s.snapshot_delta_conv,
            min_intrachain_sep=s.min_intrachain_sep, seed=s.seed, verbose=verbose,
            crosslink_method=s.crosslink_method,
        )
        node_to_res = plan.node_to_res
        layout, n_nodes = plan.layout, plan.n_nodes
    topology["config"]["sequence"] = plan.sequence
    topology["config"]["crosslink_residue"] = plan.crosslink_residue
    topology["config"]["layout"] = layout
    snapshot, note = _pick_snapshot(topology, s.snapshot, s.crosslink_method, s.allow_no_gel)
    conn = _connectivity(snapshot)
    if verbose:
        print(f"[protein] snapshot {snapshot['label']!r}: conversion {snapshot['conv']:.3f}, "
              f"{conn['n_clusters']} cluster(s), the largest holding "
              f"{conn['largest_cluster_chains']} of {conn['n_chains']} chains")

    base = "protein_network"
    summary: dict = {
        "settings": asdict(s),
        "chain": {"n_residues": plan.n_residues, "layout": layout,
                  "n_lattice_nodes": n_nodes,
                  "crosslink_residue_indices": list(plan.crosslink_residue_indices),
                  "terminal_sites_skipped": list(plan.skipped_terminal_sites)},
        "snapshot": {"label": snapshot["label"], "conversion": snapshot["conv"],
                     "n_reactions": len(snapshot.get("reactions", [])),
                     **conn,
                     "lattice": [topology["config"]["Nx"], topology["config"]["Ny"],
                                 topology["config"]["Nz"]],
                     "lattice_packing": round(topology["config"]["actual_packing"], 4),
                     "fallback_note": note},
    }

    if s.model == "charmm":
        topo_path = out / f"{base}_topology.json"
        topology_io.save_topology(topology, str(topo_path))
        summary.update(_build_charmm(s, plan, snapshot, out, base, verbose, node_to_res))
        summary["files"]["topology_json"] = str(topo_path)
    else:
        summary.update(_build_martini(s, plan, topology, snapshot, out, base, verbose,
                                      node_to_res))

    # Bonds already threaded through a ring in the as-built structure; the
    # soft stage clears most of them, and check-bonds reports what is left
    # after relaxation.
    from .bond_check import threaded_bonds, read_lammps_data
    n_threaded = len(threaded_bonds(read_lammps_data(summary["files"]["data"])))
    summary["counts"]["threaded_bonds_as_built"] = n_threaded
    if verbose:
        print(f"[protein] as built, {n_threaded} bond(s) pass through a ring; after the "
              f"relaxation run 'python -m topon.protein_network check-bonds' on the result")

    # The summary file names its files relative to the output folder, so it
    # reads the same wherever the folder is moved; the returned dict keeps
    # the full paths.
    record = {**summary, "files": {k: Path(v).resolve().relative_to(out.resolve()).as_posix()
                                   for k, v in summary["files"].items()}}
    (out / f"{base}_summary.json").write_text(json.dumps(record, indent=2, default=str),
                                             encoding="utf-8")
    return summary


def _build_charmm(s, plan, snapshot, out, base, verbose, node_to_res) -> dict:
    from .charmm.charmm_ff import CHARMMForceField
    from .charmm.workflow import DEFAULT_PRM, DEFAULT_RTF, DEFAULT_CMAP, write_charmm_system

    # User files are the whole force field. Nothing from the bundled set is
    # layered under them, so a term they lack is reported, not borrowed.
    files = list(s.charmm_files) or [str(DEFAULT_PRM), str(DEFAULT_RTF)]
    prm = next((f for f in files if f.lower().endswith((".prm", ".par"))), None)
    rtf = next((f for f in files if f.lower().endswith((".rtf", ".top"))), None)
    if prm is None or rtf is None:
        raise ValueError("charmm_files needs a topology (.rtf or .top) and a parameter "
                         "file (.prm or .par); streams (.str) and a .cmap may be added")
    extra = [f for f in files if f not in (prm, rtf)]
    ff = CHARMMForceField(prm, rtf, *[f for f in extra if not f.lower().endswith(".cmap")])
    cmap = next((f for f in extra if f.lower().endswith(".cmap")), DEFAULT_CMAP)
    res = write_charmm_system(
        ff, snapshot, list(plan.residues), node_to_res, out,
        prefix=base, water_content_pct=s.water_content, salt_conc_M=s.salt_conc,
        target_density=s.target_density, physical_backbone=s.physical_backbone,
        xpro_cis_fraction=s.xpro_cis_fraction, cmap_file=cmap, seed=s.seed,
        verbose=verbose,
    )
    files_out = {k: str(v) for k, v in res.items() if isinstance(v, Path)}
    counts = {k: v for k, v in res.items() if not isinstance(v, Path)}
    bundled = Path(DEFAULT_PRM).parent

    def shown(f):   # bundled files by name, the user's by path
        return Path(f).name if Path(f).parent == bundled else str(f)
    return {"force_field": {"model": "CHARMM36m" if not s.charmm_files else "CHARMM (user files)",
                            "files": [shown(f) for f in (prm, rtf, *extra)],
                            "cmap": "written from the PRM" if cmap == DEFAULT_CMAP else str(cmap)},
            "counts": counts, "files": files_out}


def _build_martini(s, plan, topology, snapshot, out, base, verbose, node_to_res) -> dict:
    from .martini_ff import MartiniLibrary
    from .martini_topology import chain_template_for_sequence
    from .workflow import run_protein_network

    library = MartiniLibrary.from_package_data()
    template, itp, source = chain_template_for_sequence(
        plan.sequence, itp_path=s.martini_itp, work_dir=out, name="chain")
    chain_itp = out / f"{base}_chain.itp"
    if Path(itp).resolve() != chain_itp.resolve():
        shutil.copyfile(itp, chain_itp)

    # Ions: NaCl at salt_conc in the water, plus counter-ions to neutralise.
    per_chain_mass = sum(library.get_mass(a.bead_type) for a in template.atoms)
    protein_mass = per_chain_mass * s.chains
    net = sum(a.charge for a in template.atoms) * s.chains
    if abs(net - round(net)) > 1e-6:
        raise ValueError(f"Martini chain charge {net:+.4f} is not an integer")
    net = int(round(net))
    n_nacl = 0
    if s.water_content > 0:
        water_mass = protein_mass * s.water_content / (100.0 - s.water_content)
        v_water_l = water_mass / (6.022e23 * 1000.0)       # 1 g/cm^3
        n_nacl = int(round(s.salt_conc * 6.022e23 * v_water_l))
    n_na, n_cl = n_nacl + max(0, -net), n_nacl + max(0, net)

    info: dict = {}
    paths = run_protein_network(
        block_seq=plan.sequence, n_repeats=1, n_chains=s.chains,
        output_dir=out, snapshot_label=snapshot["label"],
        segs_per_block=s.segs_per_block, target_packing=s.target_packing,
        equil_steps=s.equil_steps, seed=s.seed, base_name=base,
        water_content_pct=s.water_content, target_density_g_cm3=s.target_density,
        water_bead_type=s.water_bead, n_na_ions=n_na, n_cl_ions=n_cl,
        hierarchical_stage1=s.hierarchical_stage1, use_itp_template=True,
        chain_itp_path=str(chain_itp), library=library, verbose=verbose,
        topology=topology, node_to_res=node_to_res, strict=True, info=info,
    )
    if info.get("n_na", 0) != n_na or info.get("n_cl", 0) != n_cl:
        raise RuntimeError(f"placed {info.get('n_na')} NA and {info.get('n_cl')} CL of "
                           f"{n_na} and {n_cl} requested; lower the density")
    files = {k: str(v) for k, v in paths.items()}
    files["chain_itp"] = str(chain_itp)
    return {"force_field": {"model": "Martini 3 (Martini3-IDP bonded terms)",
                            "chain_topology": source, "files": ["martini_v3_protein.itp",
                                                                "martini_v3_water.itp"]},
            "counts": info, "files": files}
