"""The shape of a POSS node, embedded once, for the settled atomistic placement.

A POSS cage is a junction that is not one atom: an Si8O12 cube with an arm
on each corner (``POSS_AM0270``: a propyl arm that bonds to the network and
seven isooctyl arms; ``POSS``: the bare cage, whose strands bond to its
corners). The settled placement (:mod:`topon.conformation.atomistic`) draws
strands as paths and every other atom off them by a tree walk, and a walk
cannot close a cage: its last bonds end at whatever length the branches
reach. So a cage is placed whole, as a rigid body, and this module gives
the body its shape.

The shape is the node's own fragment of the network molecule: every atom
the builder made for it, its hydrogens included, and in place of each
strand atom it bonds to a stub atom of the same element (hydrogens filled
in), so the attachment atom has its real neighbours. The fragment is
embedded with the checked routine of the simbox POSS
(:func:`topon.simbox.molecule.embed_conformer`: ETKDGv3 from its own
start, MMFF, and :func:`~topon.simbox.molecule.conformer_defects`, which
refuses a bond through a ring of the molecule or a bond 15 % off its MMFF
r0, and moves to the next seed). From random starting coordinates ETKDG
tangles the AM0270 cage in 18 of 30 seeds. The conformer is then
pulled to the force field's own bond lengths: MMFF again, with every bond
of the fragment held at the r0 of the data file just written by a distance
constraint, so a DREIDING build has its Si-C at 1.697 A rather than MMFF's
1.83 to 1.93, and checked again, for a bond through a ring and against the
r0 it was held at. One template serves every node whose fragment is the
same atom for atom.

The embedding is the simbox's, reused rather than copied, so the pipeline's
cages and the simbox's come from one routine with one defect reading; its
seed count and strain limit (``topon.simbox.molecule``) reach the pipeline's
POSS builds through it. Nothing else of simbox is used.

Nothing is placed here: the template is in its own frame, and
:func:`topon.conformation.atomistic.place_bodies` turns and moves it.

The shapes of the fragments the shipped POSS demo and the POSS tests build
are stored (since 0.4.5) in ``topon/data/poss_templates.json``, as RDKit
2025.09.6 embedded them. RDKit 2026.3 embeds the same fragments
differently (a bare cage with two strands as its mirror image, the AM0270
fragment whose strand bonds through its O with its isooctyl arms in another
conformer), and every POSS build moved with it. A fragment found there, by
its signature (its atoms, bonds, r0 and stubs), takes its shape from the
file whatever RDKit is installed, and any other is embedded as before.
The stored shapes can be regenerated by embedding the same fragments again
(with :data:`STORE` set to None every fragment is embedded).
"""
from __future__ import annotations

import hashlib
import json
import numbers
from dataclasses import dataclass, field
from functools import lru_cache
from pathlib import Path

import numpy as np

#: Force constant (kcal/mol/A^2) of the distance constraints that hold every
#: bond of a template at the force field's r0. At 1e4 MMFF converges with
#: every bond of the AM0270 fragment within 0.6 % of its DREIDING r0; at 1e3
#: MMFF's own stretch terms leave Si-C 3.5 % long.
R0_HOLD = 1.0e4

#: Seeds tried for a template, from 42 upward, before a node is refused.
TEMPLATE_ATTEMPTS = 10

#: A template with a bond further than this from the r0 it was held at is
#: refused (the gate the placement answers to: no bond 15 % off its r0).
MAX_HELD_STRAIN = 0.15

#: The stored templates. None embeds every fragment (which is how the file
#: is written again).
STORE = Path(__file__).resolve().parents[1] / "data" / "poss_templates.json"


def _plain(value):
    """``value`` with every number a Python int or float, so that its repr
    does not depend on where the numbers came from (a NumPy scalar's repr
    names its type since NumPy 2)."""
    if isinstance(value, (tuple, list)):
        return tuple(_plain(v) for v in value)
    if isinstance(value, (bool, str)) or value is None:
        return value
    if isinstance(value, numbers.Integral):
        return int(value)
    if isinstance(value, numbers.Real):
        return float(value)
    return value


def signature_key(signature) -> str:
    """The store's key for a fragment signature (:func:`_signature`)."""
    return hashlib.sha256(repr(_plain(signature)).encode()).hexdigest()


@lru_cache(maxsize=4)
def _store(path) -> dict:
    """``{key: entry}`` of the stored templates at ``path`` (empty when
    there is no file)."""
    path = Path(path)
    if not path.exists():
        return {}
    return {e["key"]: e for e in json.loads(path.read_text(encoding="utf-8"))["templates"]}


def stored_template(key):
    """The stored entry for a signature key, or None."""
    return None if STORE is None else _store(str(STORE)).get(key)


@dataclass
class NodeTemplate:
    """A POSS node's shape, in its own frame.

    ``atoms`` are the network molecule's atom indices (0-based) of every
    atom of the node, heavy and hydrogen, and ``xyz`` their positions (A).
    ``stubs`` has one ``(attach, strand_atom, xyz)`` per bond from the node
    to a strand: the node atom, the strand atom it bonds to, and where the
    strand atom sits in the template. ``bonds`` are the node's bonds between
    heavy atoms and ``faces`` its rings (atom indices in ring order).
    ``centre`` is the centroid of the ring atoms (the cage) and ``core`` the
    farthest of them from it. ``max_strain`` is the largest
    ``|bond / r0 - 1|`` of the template's bonds against the force field's
    r0, and ``seed`` the embedding seed it came from.
    """

    node: int
    atoms: list
    xyz: np.ndarray
    stubs: list
    bonds: list
    faces: list
    centre: np.ndarray
    core: float
    max_strain: float = 0.0
    seed: int = 42
    signature: tuple = field(default=(), repr=False)
    #: ``"stored"`` (the stored shape) or ``"embedded"``.
    source: str = "embedded"


def poss_nodes(builder) -> dict:
    """``{node: [seed atoms]}`` for every POSS node the builder made.

    ``POSS_AM0270`` nodes are in ``builder.poss_structure`` (the cage, its
    arms and the attachment atom), bare ``POSS`` cages in
    ``builder.poss_usage`` (their corners).
    """
    out = {}
    for node, s in (getattr(builder, "poss_structure", None) or {}).items():
        seeds = list(s.get("corner_si_ids", [])) + list(s.get("cage_oxygen_ids", []))
        seeds += list(s.get("propyl_arm", {}).get("atom_ids", []))
        for arm in s.get("isooctyl_arms", {}).values():
            seeds += list(arm)
        ref = builder.node_map.get(node)
        seeds += list(ref) if isinstance(ref, (list, tuple)) else [ref]
        out[node] = sorted({int(a) for a in seeds if a is not None})
    for node in (getattr(builder, "poss_usage", None) or {}):
        ref = builder.node_map.get(node)
        seeds = list(ref) if isinstance(ref, (list, tuple)) else [ref]
        out[node] = sorted({int(a) for a in seeds if a is not None})
    return out


def _strand_atoms(builder) -> set:
    """Every atom a strand owns: backbones, bridges, side atoms and grafts."""
    out = set()
    for path in builder.edge_backbone_path.values():
        out |= {int(a) for a in path}
    for atoms in builder.edge_atom_map.values():
        out |= {int(a) for a in atoms}
    out |= {int(a) for a in builder.bridge_atoms}
    for grafts in builder.graft_atom_map.values():
        for _frac, atoms in grafts:
            out |= {int(a) for a in atoms}
    return out


def node_fragment(mol, seeds, outside) -> tuple[list, list]:
    """The node's atoms and its bonds out, read off the molecule.

    Every atom reachable from ``seeds`` without entering ``outside`` (the
    strands' atoms and other nodes'), hydrogens included, in index order;
    and ``(node atom, outside atom)`` for every bond from the node to an
    atom outside it, in the same order.
    """
    frag, stack = set(), [int(a) for a in seeds]
    while stack:
        a = stack.pop()
        if a in frag:
            continue
        frag.add(a)
        for n in mol.GetAtomWithIdx(a).GetNeighbors():
            j = n.GetIdx()
            if j not in frag and j not in outside:
                stack.append(j)
    order = sorted(frag)
    stubs = []
    for a in order:
        for n in sorted(x.GetIdx() for x in mol.GetAtomWithIdx(a).GetNeighbors()):
            if n not in frag:
                stubs.append((a, n))
    return order, stubs


def _fragment_mol(mol, order, stubs):
    """The fragment as its own molecule, a stub atom for each bond out."""
    from rdkit import Chem

    local = {a: k for k, a in enumerate(order)}
    rw = Chem.RWMol()
    for a in order:
        src = mol.GetAtomWithIdx(a)
        atom = Chem.Atom(src.GetAtomicNum())
        atom.SetFormalCharge(src.GetFormalCharge())
        atom.SetNoImplicit(True)
        rw.AddAtom(atom)
    for b in mol.GetBonds():
        i, j = b.GetBeginAtomIdx(), b.GetEndAtomIdx()
        if i in local and j in local:
            rw.AddBond(local[i], local[j], b.GetBondType())
    stub_rows = []
    for a, s in stubs:
        k = rw.AddAtom(Chem.Atom(mol.GetAtomWithIdx(s).GetAtomicNum()))
        rw.AddBond(local[a], k, mol.GetBondBetweenAtoms(a, s).GetBondType())
        stub_rows.append(k)
    frag = rw.GetMol()
    Chem.SanitizeMol(frag)
    frag = Chem.AddHs(frag)            # hydrogens on the stubs only
    return frag, local, stub_rows


def _signature(mol, order, stubs, local, bond_r0) -> tuple:
    """What makes two fragments the same template, atom for atom."""
    elems = tuple(mol.GetAtomWithIdx(a).GetAtomicNum() for a in order)
    bonds = []
    for b in mol.GetBonds():
        i, j = b.GetBeginAtomIdx(), b.GetEndAtomIdx()
        if i in local and j in local:
            r0 = bond_r0.get((min(i, j), max(i, j)))
            bonds.append((min(local[i], local[j]), max(local[i], local[j]),
                          str(b.GetBondType()), None if r0 is None else round(r0, 6)))
    out = tuple((local[a], mol.GetAtomWithIdx(s).GetAtomicNum(),
                 None if bond_r0.get((min(a, s), max(a, s))) is None
                 else round(bond_r0[(min(a, s), max(a, s))], 6)) for a, s in stubs)
    return elems, tuple(sorted(bonds)), out


def _hold_at_r0(frag, held, max_iters: int = 2000) -> None:
    """Minimise ``frag`` with every bond in ``held`` ({(i, j): r0}) kept at its r0."""
    from rdkit.Chem import AllChem, rdForceFieldHelpers

    if rdForceFieldHelpers.MMFFHasAllMoleculeParams(frag):
        props = AllChem.MMFFGetMoleculeProperties(frag)
        ff = AllChem.MMFFGetMoleculeForceField(frag, props)
        add = ff.MMFFAddDistanceConstraint
    else:
        ff = AllChem.UFFGetMoleculeForceField(frag)
        add = ff.UFFAddDistanceConstraint
    for (i, j), r0 in sorted(held.items()):
        add(int(i), int(j), False, float(r0), float(r0), R0_HOLD)
    ff.Initialize()
    ff.Minimize(maxIts=int(max_iters))


def embed_template(mol, node: int, order, stubs, bond_r0: dict, key=None) -> NodeTemplate:
    """The node's shape: the simbox's checked embedding, then the force field's r0.

    ``mol`` is the network molecule with hydrogens, ``order`` and ``stubs``
    from :func:`node_fragment`, ``bond_r0`` ``{(i, j): r0}`` over the
    molecule's atom indices (``i < j``). A fragment whose signature ``key``
    is in the store takes the stored shape instead, read against
    the same r0. Raises ``RuntimeError`` when no seed gives a
    conformer free of defects after the bonds are pulled to r0.
    """
    from rdkit import Chem

    from topon.simbox.molecule import conformer_defects, embed_conformer

    frag, local, stub_rows = _fragment_mol(mol, order, stubs)
    held = {}
    for b in frag.GetBonds():
        i, j = b.GetBeginAtomIdx(), b.GetEndAtomIdx()
        gi = order[i] if i < len(order) else None
        gj = order[j] if j < len(order) else None
        if gi is not None and gj is not None:
            r0 = bond_r0.get((min(gi, gj), max(gi, gj)))
        elif gi is not None or gj is not None:
            k = j if gi is not None else i         # the stub's row
            if k not in stub_rows:
                continue
            a, s = stubs[stub_rows.index(k)]
            r0 = bond_r0.get((min(a, s), max(a, s)))
        else:
            r0 = None
        if r0 is not None:
            held[(i, j)] = r0
    stored = None if key is None else stored_template(key)
    last: list = []
    for attempt in range(0 if stored is not None else TEMPLATE_ATTEMPTS):
        frag.RemoveAllConformers()
        seed = embed_conformer(frag, f"POSS node {node}", seed=42 + attempt,
                               max_iters=1000)
        _hold_at_r0(frag, held)
        # read again for a bond through a ring; the strain against the r0
        # the bonds were just held at (MMFF's own can be far from it: Si-H
        # 1.485 A against DREIDING's 1.257)
        last = conformer_defects(frag, max_strain=np.inf)
        X = frag.GetConformer().GetPositions()
        strain = max((abs(float(np.linalg.norm(X[i] - X[j])) / r0 - 1.0)
                      for (i, j), r0 in held.items()), default=0.0)
        if strain > MAX_HELD_STRAIN:
            last.append(f"a bond {100 * strain:.1f} % off the r0 it was held at")
        if not last:
            break
    else:
        if stored is None:
            raise RuntimeError(
                f"POSS node {node}: no conformer free of defects once its bonds are "
                f"held at the force field's r0 (seeds 42-{42 + TEMPLATE_ATTEMPTS - 1}); "
                f"the last: {'; '.join(last[:3])}")
        # the stored shape: the fragment's atoms and its stubs (the
        # hydrogens on the stubs are never read)
        X = np.full((frag.GetNumAtoms(), 3), np.nan)
        X[:len(order)] = np.asarray(stored["xyz"], float)
        X[stub_rows] = np.asarray(stored["stub_xyz"], float).reshape(-1, 3)
        seed = int(stored["seed"])
        strain = max((abs(float(np.linalg.norm(X[i] - X[j])) / r0 - 1.0)
                      for (i, j), r0 in held.items()), default=0.0)
        if strain > MAX_HELD_STRAIN:
            raise RuntimeError(f"POSS node {node}: the stored template has a bond "
                               f"{100 * strain:.1f} % off the r0 it is read against")
    rings = [list(r) for r in Chem.GetSymmSSSR(frag) if len(r) <= 12
             and all(k < len(order) for k in r)]
    ring_atoms = sorted({k for r in rings for k in r})
    heavy = [k for k in range(len(order)) if frag.GetAtomWithIdx(k).GetAtomicNum() > 1]
    centre = X[ring_atoms or heavy].mean(axis=0)
    core = float(np.linalg.norm(X[ring_atoms or heavy] - centre, axis=1).max())
    bonds = [(order[b.GetBeginAtomIdx()], order[b.GetEndAtomIdx()])
             for b in frag.GetBonds()
             if b.GetBeginAtomIdx() < len(order) and b.GetEndAtomIdx() < len(order)
             and frag.GetAtomWithIdx(b.GetBeginAtomIdx()).GetAtomicNum() > 1
             and frag.GetAtomWithIdx(b.GetEndAtomIdx()).GetAtomicNum() > 1]
    return NodeTemplate(
        node=node, atoms=list(order), xyz=X[:len(order)].copy(),
        stubs=[(a, s, X[k].copy()) for (a, s), k in zip(stubs, stub_rows)],
        bonds=bonds, faces=[[order[k] for k in r] for r in rings],
        centre=centre, core=core, max_strain=float(strain), seed=int(seed),
        source="embedded" if stored is None else "stored")


def node_templates(mol, builder, bond_r0: dict) -> list:
    """One :class:`NodeTemplate` per POSS node of the build, in node order.

    Nodes whose fragments are the same atom for atom (the same molecule,
    the same stub elements and r0) share one embedding, moved to their own
    atom indices.
    """
    nodes = poss_nodes(builder)
    if not nodes:
        return []
    strand = _strand_atoms(builder)
    other_nodes = set()
    for node, atoms in builder.node_atoms.items():
        if node not in nodes:
            other_nodes |= {int(a) for a in atoms}
    for node, ref in builder.node_map.items():
        if node not in nodes:
            other_nodes |= ({int(a) for a in ref} if isinstance(ref, (list, tuple))
                            else {int(ref)})
    out, cache = [], {}
    for node in sorted(nodes):
        outside = (strand | other_nodes) - set(nodes[node])
        order, stubs = node_fragment(mol, nodes[node], outside)
        local = {a: k for k, a in enumerate(order)}
        key = _signature(mol, order, stubs, local, bond_r0)
        if key not in cache:
            cache[key] = embed_template(mol, node, order, stubs, bond_r0,
                                        key=signature_key(key))
            cache[key].signature = key
        t = cache[key]
        if t.node == node:
            out.append(t)
            continue
        # the same fragment at another node: its atoms in the same order
        move = dict(zip(t.atoms, order))
        out.append(NodeTemplate(
            node=node, atoms=list(order), xyz=t.xyz.copy(),
            stubs=[(a, s, x.copy()) for (a, s), (_a, _s, x) in zip(stubs, t.stubs)],
            bonds=[(move[a], move[b]) for a, b in t.bonds],
            faces=[[move[a] for a in f] for f in t.faces],
            centre=t.centre.copy(), core=t.core, max_strain=t.max_strain,
            seed=t.seed, signature=key, source=t.source))
    return out


def store_entry(template: NodeTemplate, mol) -> dict:
    """A store entry for ``template`` (what the template file holds),
    with its signature key, a label (the fragment's formula and stub
    elements), the seed and the RDKit it was embedded with, and every
    position as the float it is."""
    import rdkit

    counts: dict = {}
    for a in template.atoms:
        el = mol.GetAtomWithIdx(int(a)).GetSymbol()
        counts[el] = counts.get(el, 0) + 1
    formula = "".join(f"{el}{counts[el]}" for el in sorted(counts))
    stub_el = [mol.GetAtomWithIdx(int(s)).GetSymbol() for _a, s, _x in template.stubs]
    return {"key": signature_key(template.signature),
            "label": f"{formula}, stubs {'/'.join(stub_el) or 'none'}",
            "atoms": len(template.atoms), "stubs": len(template.stubs),
            "seed": int(template.seed), "rdkit": rdkit.__version__,
            "max_strain": float(template.max_strain),
            "xyz": np.asarray(template.xyz, float).tolist(),
            "stub_xyz": [np.asarray(x, float).tolist() for _a, _s, x in template.stubs]}
